services:
  cibus.db:
    image: mysql:8
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cibus
    volumes:
      - mysql.cibus:/var/lib/mysql
volumes:
  mysql.cibus: